CREATE DATABASE   DBTRANSPORTE
GO
USE DBTRANSPORTE
GO
-- Table: ASISTENTE
CREATE TABLE ASISTENTE (
    COD_ASIS  int identity (1,1) NOT NULL,
    NOM_ASIS varchar(100)  NULL,
    APE_ASIS varchar(100)  NULL,
    DIR_ASIS varchar(100) NULL,
    DNI_ASIS char(8) NULL,
    SEXO_ASIS char(1) NULL,
    CONSTRAINT ASISTENTE_pk PRIMARY KEY  (COD_ASIS)
);

-- Table: BUS
CREATE TABLE BUS (
    COD_BUS  int identity (1,1) NOT NULL,
    RUT_BUS varchar(100)   NULL,
    PLAC_BUS char(10)  NULL,
    ASIENT_BUS int  NULL,
    HORSAL_BUS time(5)  NULL,
    HORLLE_BUS time(5)  NULL,
    LIMASIEN_BUS int   NULL,
    EVENTOS_COD_EVENT int NULL,
    EMPRESA_COD_EMP int  NULL,
    CONSTRAINT BUS_pk PRIMARY KEY  (COD_BUS)
);

-- Table: CHOFER
CREATE TABLE CHOFER (
    COD_CHOF int identity (1,1) NOT NULL,
    NOM_CHOF varchar(100)   NULL,
    APE_CHOF varchar(100) NULL,
    DIR_CHOF varchar(100) NULL,
    ASISTENTE_COD_ASIS int NULL,
    CONSTRAINT CHOFER_pk PRIMARY KEY  (COD_CHOF)
);

-- Table: DETALLE
CREATE TABLE DETALLE (
    CHOFER_COD_CHOF int identity(1,1)  NOT NULL,
    BUS_COD_BUS int NULL,
    CONSTRAINT DETALLE_pk PRIMARY KEY  (CHOFER_COD_CHOF)
);

-- Table: EMPRESA
CREATE TABLE EMPRESA (
    COD_EMP int identity(1,1) NOT NULL,
    NOM_EMP varchar(100) NULL,
    COST_EMP decimal(4,2) NULL,
    DEST_EMP varchar(100)NULL,
    CONSTRAINT EMPRESA_pk PRIMARY KEY  (COD_EMP)
);

-- Table: EVENTOS
CREATE TABLE EVENTOS (
    COD_EVENT int identity(1,1)  NOT NULL,
    CAUS_EVENT varchar(100) NULL,
    CONSTRAINT EVENTOS_pk PRIMARY KEY  (COD_EVENT)
);

-- Table: PASAJERO
CREATE TABLE PASAJERO (
    COD_PAS int identity(1,1) NOT NULL,
    NOM_PAS varchar(100)  NULL,
    APE_PAS varchar(100)  NULL,
    DNI_PAS char(8) NULL,
    SEX_PAS char(1)  NULL,
    BUS_COD_BUS int  NULL,
    CONSTRAINT PASAJERO_pk PRIMARY KEY  (COD_PAS)
);

-- foreign keys
-- Reference: BUS_EMPRESA (table: BUS)
ALTER TABLE BUS ADD CONSTRAINT BUS_EMPRESA
    FOREIGN KEY (EMPRESA_COD_EMP)
    REFERENCES EMPRESA (COD_EMP);

-- Reference: BUS_EVENTOS (table: BUS)
ALTER TABLE BUS ADD CONSTRAINT BUS_EVENTOS
    FOREIGN KEY (EVENTOS_COD_EVENT)
    REFERENCES EVENTOS (COD_EVENT);

-- Reference: CHOFER_ASISTENTE (table: CHOFER)
ALTER TABLE CHOFER ADD CONSTRAINT CHOFER_ASISTENTE
    FOREIGN KEY (ASISTENTE_COD_ASIS)
    REFERENCES ASISTENTE (COD_ASIS);

-- Reference: DETALLE_BUS (table: DETALLE)
ALTER TABLE DETALLE ADD CONSTRAINT DETALLE_BUS
    FOREIGN KEY (BUS_COD_BUS)
    REFERENCES BUS (COD_BUS);

-- Reference: DETALLE_CHOFER (table: DETALLE)
ALTER TABLE DETALLE ADD CONSTRAINT DETALLE_CHOFER
    FOREIGN KEY (CHOFER_COD_CHOF)
    REFERENCES CHOFER (COD_CHOF);

-- Reference: PASAJERO_BUS (table: PASAJERO)
ALTER TABLE PASAJERO ADD CONSTRAINT PASAJERO_BUS
    FOREIGN KEY (BUS_COD_BUS)
    REFERENCES BUS (COD_BUS);

-- End of file.





------ STORES PROCEDURE----------



CREATE PROCEDURE LISTARASISTENTE
AS
BEGIN
SELECT * FROM ASISTENTE
END

EXEC LISTARASISTENTE




create procedure INSERTASISTENTE
@NOM_ASIS VARCHAR(100),
@APE_ASIS VARCHAR(100),
@DIR_ASIS VARCHAR(100),
@DNI_ASIS CHAR(8),
@SEXO_ASIS CHAR(1)
AS
BEGIN
INSERT INTO ASISTENTE (NOM_ASIS,APE_ASIS,DIR_ASIS,DNI_ASIS,SEXO_ASIS) VALUES (@NOM_ASIS,@APE_ASIS,@DIR_ASIS,@DNI_ASIS,@SEXO_ASIS)
END
GO

EXEC INSERTASISTENTE @NOM_ASIS='ZECARLOS',@APE_ASIS='SALCEDO',@DIR_ASIS='IMPERIAL',@DNI_ASIS='77224643',@SEXO_ASIS='M'


CREATE PROCEDURE DELETEASISTENTE
@COD_ASIS INT
AS
BEGIN
DELETE FROM ASISTENTE WHERE COD_ASIS=@COD_ASIS
END
GO

EXEC DELETEASISTENTE @COD_ASIS='1'


CREATE PROCEDURE UPDATEASISTENTE
@COD_ASIS INT,
@NOM_ASIS VARCHAR(100),
@APE_ASIS VARCHAR(100),
@DIR_ASIS VARCHAR(100),
@DNI_ASIS CHAR(8),
@SEXO_ASIS CHAR(1)
AS
BEGIN
UPDATE ASISTENTE SET NOM_ASIS=@NOM_ASIS, APE_ASIS=@APE_ASIS, DIR_ASIS=@DIR_ASIS, DNI_ASIS=@DNI_ASIS, SEXO_ASIS=@SEXO_ASIS   WHERE COD_ASIS=@COD_ASIS
END
GO

EXEC UPDATEASISTENTE @NOM_ASIS='ZECARLO', @APE_ASIS='DEL MAZO',@DIR_ASIS='IMPERIAL', @DNI_ASIS='77224643', @SEXO_ASIS='M', @COD_ASIS='1'


CREATE PROCEDURE INSERTBUS
@RUT_BUS VARCHAR(100),
@PLAC_BUS CHAR(10),
@ASIENT_BUS INT,
@HORSAL_BUS TIME(5),
@HORLLE_BUS TIME(5),
@EVENTOS_COD_EVENT INT,
@EMPRESA_COD_EMP INT 
AS
BEGIN
INSERT INTO BUS (RUT_BUS, PLAC_BUS ,ASIENT_BUS  ,HORSAL_BUS, HORLLE_BUS , EVENTOS_COD_EVENT,  EMPRESA_COD_EMP) VALUES
                ('LIMA-CAÑETE', 'KLGHQPEULR', '50','9:30','11:30','1','1')
	

INSERT INTO EVENTOS (CAUS_EVENT) VALUES ('CHOQUE')
SELECT * FROM EVENTOS

SELECT * FROM EMPRESA 
INSERT INTO EMPRESA (NOM_EMP, COST_EMP, DEST_EMP) VALUES ('SOYUS', '30.00', 'LIMA CAÑETE')

SELECT * FROM BUS 